#!/usr/bin/python
# This file is part of Openplotter.
# Copyright (C) 2015 by sailoog <https://github.com/sailoog/openplotter>
#
# Openplotter is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# any later version.
# Openplotter is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Openplotter. If not, see <http://www.gnu.org/licenses/>.

import socket, datetime, sys
from classes.check_vessel_self import checkVesselSelf

vessel_self=checkVesselSelf()
mmsi=vessel_self.mmsi


sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

def sendSK(keyword,source):
	value='{"message": "'+keyword+'"}'
	path='notifications.keyword.'+source
	SignalK='{"mmsi":"'+mmsi+'","updates":[{"source":{"type": "notifications","src":"'+source+'"},"values":[{"path":"'+path+'","value":'+value+'}]}]}\n'
	sock.sendto(SignalK, ('127.0.0.1', 55558))

try: 
	source=sys.argv[1]
except:
	keyword='null'
	source='opencpn'
	sendSK(keyword,source)
	source='sms'
	sendSK(keyword,source)
	source='undefined'
	sendSK(keyword,source)
else:
	try:
		keyword=sys.argv[2]
	except:
		keyword=sys.argv[1]
		source='undefined'
		sendSK(keyword,source)
	else:
		keyword=sys.argv[2]
		source=sys.argv[1]
		if source!='opencpn' and source!='sms': source='undefined'
		sendSK(keyword,source)
